### ISSUE TITLE
评论只有一页

### ISSUE THREAD

**Issue by Scrooge20291224** [hxdnshx/NeteaseMusicAPI#1]
想问下有没有办法获取全部的评论？直接调用GetComments看Key为comments只能得到第一页的评论，希望得到您的指点，谢谢！

**Comment by hxdnshx** [comment]
你可以尝试设定Offset参数获取后面的评论0 0

**Comment by Scrooge20291224** [comment]
> 你可以尝试设定Offset参数获取后面的评论0 0

感激不尽！马上试试！

**Comment by Scrooge20291224** [comment]
赞！
